export const TIMELINE = [
    {
        company: "VideoVerse",
        role: "Staff Engineer",
        period: "January 2025 — Now",
        location: "Remote, India",
        stack: [
            "SNS/SQS",
            "Cloud Storage",
            "Webhooks",
            "FTP/SFTP",
            "APM",
            "Tracing",
            "PagerDuty",
            "Datadog",
            "Last9",
            "Playwright",
            "AI-assisted workflows",
        ],
        bullets: [
            "Designed event-driven architecture (SNS/SQS) processing ~7M lifecycle events/month across clips, streams, and publishing; replaced synchronous workflows with independently scalable consumers enabling parallel team execution",
            "Scaled media distribution platform for 100+ enterprise customers and 50K+ monthly workflows across 10+ integrations (cloud storage, webhooks, social, FTP/SFTP); improved reliability via retries and failure isolation",
            "Defined observability and incident-response standards across 30+ services (APM, tracing, alerting, synthetics, PagerDuty); reduced production acknowledgment time from 20–30 min to <2 min and improved post-deploy issue detection",
            "Led observability migration from Datadog → Last9 across 30+ services; preserved SLOs/alert fidelity while achieving ~60% cost reduction in ~4 weeks",
            "Built engineering productivity and quality systems for a 20-person team; scaled Playwright automation (~60% critical flows), post-deploy validation (~40%), and AI-assisted engineering workflows with repo-level guardrails",
            "For referrals: [manish.bisht@magnifi.ai](mailto:manish.bisht@magnifi.ai).",
        ],
        metric: { label: "dev teams + QA team", delta: "3 + 1" },
        current: true,
    },
    {
        company: "VideoVerse",
        role: "Lead Engineer",
        period: "January 2024 - December 2024",
        location: "Remote, India",
        stack: [
            "Microservices",
            "Serverless",
            "CI/CD",
            "E2E",
            "Prettier",
            "ESLint",
            "SonarQube",
            "GitLeaks",
            "Progressive Rollouts",
        ],
        bullets: [
            "Led V2 platform modernization for a media product serving 100+ enterprise customers and 550K+ clips/month; designed phased migration across 40+ routes and decomposed the monolith into ~5 microservices and 20+ serverless workloads enabling zero-downtime, independent releases",
            "Redesigned CI/CD and release governance for a ~20-engineer team; replaced biweekly deployments with daily production releases via automated quality gates (lint, static analysis, E2E) and progressive rollout strategies",
            "Defined engineering foundation standards across frontend, backend, and serverless systems; standardized repo structure, quality tooling (Prettier, ESLint, SonarQube, GitLeaks), and onboarding - reducing new engineer ramp-up time from 2–3 weeks to < 1 week",
            "For referrals: [manish.bisht@magnifi.ai](mailto:manish.bisht@magnifi.ai).",
        ],
        metric: { label: "migration", delta: "v2" },
    },
    {
        company: "Let's Dive",
        role: "Software Development Engineer II",
        period: "December 2020 - December 2023",
        location: "Remote, India",
        stack: [
            "Web",
            "Chrome Extension",
            "Zoom",
            "AI Note-taking",
            "Frontend Architecture",
            "Release Management",
            "QA Automation",
        ],
        bullets: [
            "Founding engineer at a B2B SaaS startup acquired by VideoVerse; built and shipped product experiences across web, Chrome Extension, and Zoom as the company evolved into an AI note-taking platform",
            "Acted as frontend tech lead partnering with CEO/CTO on technical scope, release management, and cross-surface delivery while mentoring engineers on architecture and deployment workflows",
            "Owned end-to-end product and engineering execution - core feature delivery, release quality, QA automation, onboarding, and product-health improvements",
            "For referrals: [manish@letsdive.io](mailto:manish@letsdive.io).",
        ],
        metric: { label: "Founding Engineer", delta: "#3" },
    },
    {
        company: "BookMyShow",
        role: "Software Development Engineer",
        period: "September 2019 - November 2020",
        location: "Mumbai, Maharashtra, India",
        stack: [
            "APIs",
            "Mobile Web",
            "Desktop Web",
            "PhonePe",
            "SSO",
            "OTP",
            "PHP",
            "Nginx",
            "HAProxy",
            "Cookie Security",
        ],
        bullets: [
            "Built API-driven home and listings experiences across mobile and desktop platforms.",
            "Reduced mobile website server error logs by 94%.",
            "Implemented PhonePe Integration, including SSO Login, on mobile website.",
            "Designed and deployed one-time password (OTP) login module on mobile website.",
            "Optimized mobile website login pages by eliminating PHP codebase.",
            "Developed modern header and footer components for mobile website.",
            "Migrated mobile website redirection logics from Nginx to HAProxy for improved performance.",
            "Strengthened user-specific cookie security for enhanced safety.",
            "Part of Web Platform, Members and Discovery Team.",
            "For referrals: [manish.bisht@bookmyshow.com](mailto:manish.bisht@bookmyshow.com).",
        ],
        metric: { label: "server error logs", delta: "−94%" },
    },
    {
        company: "Covalent Capital",
        role: "Software Engineer",
        period: "May 2018 - August 2019",
        location: "Bangalore, Karnataka, India",
        stack: [
            "React",
            "React Native",
            "iOS",
            "Android",
            "PWA",
            "Push Notifications",
            "Web Components",
            "Webpack",
        ],
        bullets: [
            "Configured development and staging servers.",
            "Developed React Native app for iOS and Android.",
            "Converted Web/Mobile versions to PWA.",
            "Implemented Push Notifications and Add to Home Screen functionality for PWA.",
            "Created Web and Mobile versions of Order Management and Allocation System (OMAS).",
            "Designed custom web components like Input, Table, Select, AutoComplete, SVG, etc.",
            "Optimized production build size by 85% by updating webpack from v1 to v4.",
            "Upgraded ReactJS and other libraries from v15.4 to v16.8, improving overall performance.",
            "Streamlined FrontEnd Code and File Structure of OMAS.",
            "For referrals: [manish@covacap.com](mailto:manish@covacap.com).",
        ],
        metric: { label: "production build size", delta: "−85%" },
    },
    {
        company: "BlueCube Network",
        role: "Software Engineering Intern",
        period: "May 2016 - June 2016",
        location: "Jaipur, Rajasthan, India",
        stack: ["Admin Dashboard", "HTML", "CSS", "JavaScript"],
        bullets: [
            "Collaborated with two interns to develop an admin dashboard for perfmon.io, providing user, website, and system stats to increase profits and reduce product costs.",
            "Designed and coded one-page Drone Buying Guide using HTML, CSS, and JavaScript.",
        ],
        metric: { label: "intern team", delta: "3" },
    },
    {
        company: "Run4Offers",
        role: "Founder/CEO",
        period: "July 2015 - December 2015",
        location: "Jaipur, Rajasthan, India",
        stack: [
            "Affiliate Portal",
            "Cashback",
            "Website Development",
            "Promotions",
            "Operations",
        ],
        bullets: [
            "Created affiliate portal for cashback on partner shopping orders from Amazon, Flipkart, etc.",
            "Achieved 15k monthly website views within two months of launch.",
            "Conducted successful promotional stall within college campus with team.",
            "Designed and developed entire website.",
            "Managed operations to break even with no profit or loss.",
        ],
        metric: { label: "monthly website views", delta: "15k+" },
    },
];

export const OPEN_SOURCE = [
    {
        company: "Facebook Open Source",
        role: "Student Developer · Facebook Instant Articles",
        period: "February 2018 - May 2018",
        location: "Remote",
        stack: [
            "Facebook Instant Articles",
            "SDK",
            "Rules Editor",
            "instantarticles.fb.com",
        ],
        bullets: [
            "Completed 6-week mentorship program in Facebook Open Source.",
            "Contributed to Facebook Instant Articles, including SDK and Rules Editor.",
            "Worked directly on [instantarticles.fb.com](https://instantarticles.fb.com).",
            "[Pull requests: facebook-instant-articles-sdk-php](https://github.com/facebook/facebook-instant-articles-sdk-php/pulls?q=is%3Apr+author%3Amanishbisht)",
            "[Pull requests: facebook-instant-articles-rules-editor](https://github.com/facebook/facebook-instant-articles-rules-editor/pulls?q=is%3Apr+author%3Amanishbisht)",
        ],
        metric: { label: "PRs shipped", delta: "3" },
    },
    {
        company: "Google Summer of Code",
        role: "GSoC Contributor · phpmyadmin",
        period: "May 2017 - August 2017",
        location: "Remote",
        stack: [
            "phpmyadmin",
            "Core Maintenance",
            "Issue Triage",
            "Open Source",
        ],
        bullets: [
            "Addressed major issues and made improvements to phpmyadmin core project.",
            "Worked to reduce the high number (~210) of open issues.",
            "Contributed to maintaining and enhancing phpmyadmin's functionality.",
            "[Pull requests: phpmyadmin](https://github.com/phpmyadmin/phpmyadmin/pulls?q=author%3Amanishbisht)",
            "[Issues authored: phpmyadmin](https://github.com/phpmyadmin/phpmyadmin/issues?q=author%3Amanishbisht)",
            "[Issues mentioning Manish: phpmyadmin](https://github.com/phpmyadmin/phpmyadmin/issues?q=mentions%3Amanishbisht)",
            "[Project summary](https://goo.gl/wHfQjS)",
        ],
        metric: { label: "PRs shipped", delta: "18" },
    },
];
