export const TIMELINE = [
    {
        company: "VideoVerse",
        role: "Staff Engineer · Frontend Platform",
        period: "2023 — Now",
        location: "Remote · India",
        stack: ["React", "TypeScript", "Next.js", "AWS", "Playwright"],
        bullets: [
            "Own the frontend platform — design system, build pipeline, observability, CI/CD.",
            "Led the migration to a typed module-federation monorepo. 12 packages, single deploy.",
            "Cut p95 latency on the editor by 38% (Q1 2024).",
            "Built the in-house Playwright + visual-regression test infra. 87% coverage at 9-min CI.",
        ],
        metric: { label: "p95 latency", delta: "−38%" },
        current: true,
    },
    {
        company: "BookMyShow",
        role: "Senior Software Engineer · Checkout",
        period: "2020 — 2023",
        location: "Mumbai, India",
        stack: ["React", "Node.js", "AWS", "Redis", "Datadog"],
        bullets: [
            "Architected the new checkout flow serving 30M+ monthly transactions across 6 markets.",
            "Reduced server errors by 94% over two quarters via typed contracts + idempotency.",
            "Mentored a team of 8 engineers across India and Indonesia. Three reached SDE-3.",
            "Owned on-call rotation. Drove MTTR from 47m to 9m.",
        ],
        metric: { label: "server errors", delta: "−94%" },
    },
    {
        company: "Let's Dive",
        role: "Founding Engineer",
        period: "2019 — 2020",
        location: "Bangalore, India",
        stack: ["React Native", "Node.js", "GCP"],
        bullets: [
            "Joined as engineer #1. Shipped the first three versions of the consumer app.",
            "Built the realtime audio infra on top of LiveKit before LiveKit was cool.",
            "Set the engineering hiring bar and ran every loop for the next year.",
        ],
        metric: { label: "engineer", delta: "#1" },
    },
    {
        company: "Covalent Capital",
        role: "Software Engineer · Trading",
        period: "2018 — 2019",
        location: "Mumbai, India",
        stack: ["Python", "JavaScript", "PostgreSQL"],
        bullets: [
            "Wrote the internal portfolio analytics dashboard used by the trading desk.",
            "Maintained latency-sensitive market data pipelines.",
        ],
        metric: { label: "dashboards", delta: "12" },
    },
    {
        company: "Facebook Open Source",
        role: "Open Source Mentor · F8 Scholar",
        period: "2018 — 2019",
        location: "Remote",
        stack: ["React", "Jest", "Docusaurus"],
        bullets: [
            "Mentored contributors to Jest and Docusaurus.",
            "F8 Scholar 2018 and 2019. Spoke at three regional React meetups.",
        ],
        metric: { label: "F8 scholar", delta: "×2" },
    },
    {
        company: "Google Summer of Code",
        role: "GSoC Contributor · Systers Open Source",
        period: "2017",
        location: "Remote",
        stack: ["React", "Redux", "Firebase"],
        bullets: [
            "Built the Mentorship System web app for Anita B.org / Systers.",
            "Shipped 14k LOC and 47 PRs over the summer. Project remained the org's reference codebase.",
        ],
        metric: { label: "PRs shipped", delta: "47" },
    },
];
