export const TIMELINE = [
    {
        company: "VideoVerse",
        role: "Staff Engineer",
        period: "January 2025 — Now",
        location: "Remote, India",
        stack: [
            "React",
            "TypeScript",
            "Node.js",
            "NestJS",
            "AWS",
            "Playwright",
            "AI Coding",
        ],
        bullets: [
            "Driving full-stack technical strategy across frontend platforms, backend services, cloud infrastructure, observability systems, and developer tooling initiatives powering large-scale media workflows.",
            "Leading architecture modernization efforts for the v2 platform, including scalable React/TypeScript frontend systems, backend APIs, release workflows, and cloud-native engineering practices.",
            "Built standardized engineering workflows around CI/CD, semantic releases, feature flags, automated code quality checks, Datadog observability, and production monitoring to improve deployment reliability and developer productivity.",
            "Spearheaded adoption of AI-assisted engineering workflows by evaluating and enabling tools like Cursor/Claude/ChatGPT across teams, while improving engineering standards, PR quality, and development velocity.",
            "Owned cross-functional engineering initiatives spanning hiring, mentorship, QA alignment, release management, E2E testing strategy, onboarding, architecture reviews, and end-to-end production ownership across multiple pods.",
            "For referrals: [manish.bisht@magnifi.ai](mailto:manish.bisht@magnifi.ai).",
        ],
        metric: { label: "dev teams + QA team", delta: "2 + 1" },
        current: true,
    },
    {
        company: "VideoVerse",
        role: "Lead Engineer",
        period: "January 2024 - December 2024",
        location: "Remote, India",
        stack: ["React", "TypeScript", "Node.js", "AWS", "Playwright"],
        bullets: [
            "Led end-to-end delivery of scalable full-stack product initiatives across frontend applications, backend services, APIs, search workflows, and cloud deployments with ownership from planning to production rollout.",
            "Built the foundation for the next-generation v2 platform architecture with reusable frontend patterns, scalable state management, modular backend integrations, and improved developer workflows.",
            "Expanded automated testing coverage using Playwright and strengthened QA processes by improving test strategies, release confidence, staging validation, and production-readiness workflows.",
            "Optimized engineering execution through feature-flag-driven development, improved branching strategies, semantic versioning workflows, and faster production deployment practices.",
            "Mentored and onboarded engineers across pods through technical guidance, PR reviews, debugging support, knowledge-sharing sessions, hiring participation, and engineering best-practice initiatives.",
            "For referrals: [manish.bisht@magnifi.ai](mailto:manish.bisht@magnifi.ai).",
        ],
        metric: { label: "migration", delta: "v2" },
    },
    {
        company: "Let's Dive",
        role: "Software Development Engineer II",
        period: "December 2020 - December 2023",
        location: "Remote, India",
        stack: ["React", "Node.js", "Chrome Extension", "Zoom SDK", "AWS"],
        bullets: [
            "Founding engineer who built and shipped across web, Chrome Extension, and Zoom at a B2B SaaS startup that evolved from a meeting engagement platform to an AI-powered note-taking product - from zero to acqui-hire by [VideoVerse](https://vverse.ai).",
            "Acted as de facto frontend tech lead - partnered directly with CEO and CTO on technical decisions and release scope, owned the frontend release pipeline, managed cross-surface releases across web, Chrome Extension, and Zoom, conducted pre-sprint design reviews, and mentored incoming engineers on deployment workflows and architecture patterns.",
            "Owned and shipped core product features end-to-end - Meeting Collections, standalone agenda, meeting search, pricing & seat assignment, meeting tags, external member access, consent flows and more across the full dev-to-prod lifecycle including feature flagging, QA coordination, and staged rollouts.",
            "Demonstrated a product engineer mindset - proactively monitored Chrome Extension adoption metrics, surfaced a signup regression blocking 36% of active users, and cross-referenced customer reports with bug tickets to verify fixes before closure; consistently bridged the gap between engineering output and real user impact.",
            "Strengthened engineering foundations across the team - drove QA automation adoption, contributed to hiring, and onboarded multiple engineers on codebase conventions and deployment workflows.",
            "For referrals: [manish@letsdive.io](mailto:manish@letsdive.io).",
        ],
        metric: { label: "Founding Engineer", delta: "#3" },
    },
    {
        company: "BookMyShow",
        role: "Software Development Engineer",
        period: "September 2019 - November 2020",
        location: "Mumbai, Maharashtra, India",
        stack: [
            "React",
            "Javascript",
            "Typsescript",
            "Node.js",
            "AWS",
            "Redis",
        ],
        bullets: [
            "Created API-driven home and listings pages for mobile and desktop.",
            "Reduced mobile website server error logs by 94%.",
            "Implemented PhonePe Integration, including SSO Login, on mobile website.",
            "Designed and deployed one-time password (OTP) login module on mobile website.",
            "Optimized mobile website login pages by eliminating PHP codebase.",
            "Developed modern header and footer components for mobile website.",
            "Migrated mobile website redirection logics from Nginx to HAProxy for improved performance.",
            "Strengthened user-specific cookie security for enhanced safety.",
            "Part of Web Platform, Members and Discovery Team.",
            "For referrals: [manish.bisht@bookmyshow.com](mailto:manish.bisht@bookmyshow.com).",
        ],
        metric: { label: "server error logs", delta: "−94%" },
    },
    {
        company: "Covalent Capital",
        role: "Software Engineer",
        period: "May 2018 - August 2019",
        location: "Bangalore, Karnataka, India",
        stack: ["React", "React Native", "Node.js", "AWS", "GCP"],
        bullets: [
            "Configured development and staging servers.",
            "Developed React Native app for iOS and Android.",
            "Converted Web/Mobile versions to PWA.",
            "Implemented Push Notifications and Add to Home Screen functionality for PWA.",
            "Created Web and Mobile versions of Order Management and Allocation System (OMAS).",
            "Designed custom web components like Input, Table, Select, AutoComplete, SVG, etc.",
            "Optimized production build size by 85% by updating webpack from v1 to v4.",
            "Upgraded ReactJS and other libraries from v15.4 to v16.8, improving overall performance.",
            "Streamlined FrontEnd Code and File Structure of OMAS.",
            "For referrals: [manish@covacap.com](mailto:manish@covacap.com).",
        ],
        metric: { label: "production build size", delta: "−85%" },
    },
    {
        company: "BlueCube Network",
        role: "Software Engineering Intern",
        period: "May 2016 - June 2016",
        location: "Jaipur, Rajasthan, India",
        stack: ["React", "PHP", "Node.js", "AWS"],
        bullets: [
            "Collaborated with two interns to develop an admin dashboard for perfmon.io, providing user, website, and system stats to increase profits and reduce product costs.",
            "Designed and coded one-page Drone Buying Guide using HTML, CSS, and JavaScript.",
        ],
        metric: { label: "intern team", delta: "3" },
    },
    {
        company: "Run4Offers",
        role: "Founder/CEO",
        period: "July 2015 - December 2015",
        location: "Jaipur, Rajasthan, India",
        stack: ["PHP", "Node.js", "My SQL", "AWS"],
        bullets: [
            "Created affiliate portal for cashback on partner shopping orders from Amazon, Flipkart, etc.",
            "Achieved 15k monthly website views within two months of launch.",
            "Conducted successful promotional stall within college campus with team.",
            "Designed and developed entire website.",
            "Managed operations to break even with no profit or loss.",
        ],
        metric: { label: "monthly website views", delta: "15k+" },
    },
];

export const OPEN_SOURCE = [
    {
        company: "Facebook Open Source",
        role: "Student Developer · Facebook Instant Articles",
        period: "February 2018 - May 2018",
        location: "Remote",
        stack: ["React", "PHP", "HTML", "CSS", "Facebook Instant Articles"],
        bullets: [
            "Completed 6-week mentorship program in Facebook Open Source.",
            "Contributed to Facebook Instant Articles, including SDK and Rules Editor.",
            "Worked directly on [instantarticles.fb.com](https://instantarticles.fb.com).",
            "[Pull requests: facebook-instant-articles-sdk-php](https://github.com/facebook/facebook-instant-articles-sdk-php/pulls?q=is%3Apr+author%3Amanishbisht)",
            "[Pull requests: facebook-instant-articles-rules-editor](https://github.com/facebook/facebook-instant-articles-rules-editor/pulls?q=is%3Apr+author%3Amanishbisht)",
        ],
        metric: { label: "PRs shipped", delta: "3" },
    },
    {
        company: "Google Summer of Code",
        role: "GSoC Contributor · phpmyadmin",
        period: "May 2017 - August 2017",
        location: "Remote",
        stack: [
            "PHP",
            "Javascript",
            "TypeSecript",
            "CSS",
            "MySQL",
            "phpmyadmin",
        ],
        bullets: [
            "Addressed major issues and made improvements to phpmyadmin core project.",
            "Worked to reduce the high number (~210) of open issues.",
            "Contributed to maintaining and enhancing phpmyadmin's functionality.",
            "[Pull requests: phpmyadmin](https://github.com/phpmyadmin/phpmyadmin/pulls?q=author%3Amanishbisht)",
            "[Issues authored: phpmyadmin](https://github.com/phpmyadmin/phpmyadmin/issues?q=author%3Amanishbisht)",
            "[Issues mentioning Manish: phpmyadmin](https://github.com/phpmyadmin/phpmyadmin/issues?q=mentions%3Amanishbisht)",
            "[Project summary](https://goo.gl/wHfQjS)",
        ],
        metric: { label: "PRs shipped", delta: "18" },
    },
];
